export default function handler(req, res) {
    const appUrl = process.env.NEXT_PUBLIC_APP_URL;
    const data = [ 
            {
                'name':'goldenmusic2025',
                'home':{
                    'title':'2025第36屆金曲獎直播＆得獎名單｜紅毯星光大道一次看',
                    'description':'2025金曲獎完整資訊看這裡！第36屆金曲獎直播、得獎名單、星光大道紅毯、最佳男女歌手獎落誰家？精彩表演一次掌握，鎖定最強音樂盛典。',
                    'keywords':'金曲獎,金曲獎直播,金曲獎得獎名單,2025金曲獎,第36屆金曲獎,金曲獎表演,金曲獎得主,金曲獎女歌手,金曲獎主持人,金曲獎男歌手,金曲獎名單,金曲獎紅毯,金曲獎歷屆得獎名單,金曲獎星光大道,金曲獎線上看,金曲獎電視轉播',
                },
                'winners':{
                    'title':'2025金曲獎得獎名單｜第36屆金曲獎入圍歌手與獲獎作品一次看',
                    'description':'2025第36屆金曲獎入圍暨得獎名單出爐！金曲獎最佳男歌手、女歌手、年度歌曲、專輯、最佳新人等所有獲獎名單一次完整整理。',
                    'keywords':'金曲獎得獎名單,金曲獎得主,金曲獎女歌手,金曲獎男歌手,2025金曲獎得獎名單,第36屆金曲獎得獎名單,金曲獎入圍名單,2025金曲獎入圍名單,第36屆金曲獎入圍名單',
                },
                'highlights':{
                    'title':'2025金曲獎焦點新聞｜人物專訪、紅毯亮點、頒獎典禮表演一次看',
                    'description':'2025金曲獎新聞不漏接！《TVBS新聞網》專訪入圍歌手，看主持人精彩橋段、頒獎典禮表演、紅毯亮點、得獎感言與話題事件，第36屆金曲獎即時更新新聞一次掌握！',
                    'keywords':'金曲獎得獎名單,金曲獎得主,金曲獎女歌手,金曲獎男歌手,2025金曲獎得獎名單,第36屆金曲獎得獎名單,金曲獎入圍名單,2025金曲獎入圍名單,第36屆金曲獎入圍名單',
                },
            },
            {
                'name':'goldenbells2025',
                'home':{
                    'title':'',
                    'description':'',
                    'keywords':'',
                },
                'winners':{
                    'title':'',
                    'description':'',
                    'keywords':'',
                },
                'highlights':{
                    'title':'',
                    'description':'',
                    'keywords':'',
                },
            },
            {
                'name':'goldenhorse2025',
                'home':{
                    'title':'',
                    'description':'',
                    'keywords':'',
                },
                'winners':{
                    'title':'',
                    'description':'',
                    'keywords':'',
                },
                'highlights':{
                    'title':'',
                    'description':'',
                    'keywords':'',
                },
            },
    ];
    res.status(200).json(data);
}